apiVersion: v1
kind: Service
metadata:
  name: {{ include "tool-openweathermap.fullname" . }}
  labels:
{{ include "tool-openweathermap.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "tool-openweathermap.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
